language: android
sudo: true
branches:
  only:
  - master
deploy:
  skip_cleanup: true
android:
  components:
  - platform-tools
  - build-tools
  - android-22
before_install:
- nvm install 0.12
- npm install -g cordova
- npm install -g ionic
# install gcc-4.9 and g++-4.9
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update; sudo apt-get install gcc-4.9 g++-4.9
- sudo rm /usr/bin/gcc
- sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
- sudo rm /usr/bin/g++
- sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++

install:
# clone tilemaker
- git clone -b master --single-branch https://github.com/mapbox/mason.git ~/.mason
- git clone https://github.com/systemed/tilemaker.git
- cd tilemaker
# install dependencies
- ~/.mason/mason install protobuf 2.6.1
- ~/.mason/mason link protobuf 2.6.1
- ~/.mason/mason install protobuf_c 1.1.0
- ~/.mason/mason link protobuf_c 1.1.0
- ~/.mason/mason install boost 1.57.0
- ~/.mason/mason link boost 1.57.0
- ~/.mason/mason install boost_libfilesystem 1.57.0
- ~/.mason/mason link boost_libfilesystem 1.57.0
- ~/.mason/mason install boost_libsystem 1.57.0
- ~/.mason/mason link boost_libsystem 1.57.0
- ~/.mason/mason install boost_libthread 1.57.0
- ~/.mason/mason link boost_libthread 1.57.0
- ~/.mason/mason install boost_libprogram_options 1.57.0
- ~/.mason/mason link boost_libprogram_options 1.57.0
- ~/.mason/mason install lua 5.1.0
- ~/.mason/mason link lua 5.1.0
- ~/.mason/mason install luabind_lua51 dev
- ~/.mason/mason link luabind_lua51 dev
- ~/.mason/mason install sqlite 3.8.10.2
- ~/.mason/mason link sqlite 3.8.10.2
# build and install tilemaker (modified compilation flags)
- export CPATH=./mason_packages/.link/include
- export LIBRARY_PATH=./mason_packages/.link/lib
- export PATH=$PATH:$PWD/mason_packages/.link/bin
- export LUA_CFLAGS=$(~/.mason/mason cflags lua 5.1.0)
- export LUA_LIBS=$(~/.mason/mason ldflags lua 5.1.0)
#- sed -i '1s|.*|LUA_CFLAGS := '"$LUA_CFLAGS"'|' Makefile
- sed -i '2s|.*|LUA_LIBS := -llua|' Makefile
- sed -i '3s|.*|CXXFLAGS := -O3 -Wall -Wno-unknown-pragmas -Wno-sign-compare -std=c++11 -pthread -Wl,--no-as-needed -ldl|' Makefile
- cat Makefile
- make
- sudo make install
- cd ..
#- wget -O output.osm.pbf http://www.overpass-api.de/api/xapi?*[bbox=9.9725,53.53494,10.03017,53.56594]
- wget -O input.osm.pbf http://download.geofabrik.de/europe/faroe-islands-latest.osm.pbf
- tilemaker --config=./config.json --process=./process.lua ./input.osm.pbf --output=./www/hamburg.mbtiles
- git log --format=%B -n 1 $TRAVIS_COMMIT
script:
- cordova -v
- ionic info
- ionic browser list
- ionic browser add crosswalk@14.42.334.0
- cordova plugin add cordova-sqlite-storage
- ionic build android
- ls platforms/android/build/outputs/apk/
- "/bin/cp platforms/android/build/outputs/apk/android-armv7-debug.apk dev/android-armv7-debug.apk"
- sh ./dev/scripts/github.sh
env:
  global:
  - secure: sHVFWJxH6ZKHYEfjj+mk8o/uWdkt+8lQWZtUbpgANPCV55rpEtPrb2LbMVTF78DZVH57yGHCXSig9Bl/RnDVUppMnrwBIY+irz4idzyFcKFC4PFqLiqqegD66w1QNlQKeXFRbkRAgluHtUZz1B03MURY8NhKxW9vJEiwc/wAuoZEnCd30fvRe3khrZU0UDVwqqHiqYCZxsuBCzXv++b85SZ7NAm8mFREKLs0DUPzQN4J2aNJX1km2Xhz5UoU/vtfDVwjssXtBEeg+IDz4EnBdWZE2Ef2XGZKptxfRlDExSvxQNi3+sCtiCHC1vw/Y29oevSL4K3xnAxcerLh0B5ncwyQiHELkhO7er05zoKJdyMnZoRX5bvnDqj6Yk/JhBI+gB8qT8yUl0c+Uy0nJ2d61lVjbxylghd3ZFuH9JJ9rfmjW5+aEvccvhzizC1R8W+XNYb+vy2iEzbilGHxVmU485Tjg3h5vwvYK2C+9efAnrT8TjOL8iZbYZkTZJnbySYSmhgLgjkRO+Tz43zMbODzEQRfqc+W9DjviwPIRv6+fZMdcD1Q0ngMWu936A5lafHfh7+guSFJ+QTWD2TZ7l4cdGuV2B+lNc2tpSOPH0oi6GnHztRAcBcXgEKH9+1jrM7kVdBNPX4q8+IyABSFuQI74p8FAXAPpi5MrRpiTeIAvqQ=

