language: android
sudo: required
branches:
  only:
  - master
deploy:
  skip_cleanup: true
android:
  components:
  - platform-tools
  - build-tools
  - android-22
before_install:
- nvm install 0.12
- npm install -g cordova
- npm install -g ionic
- git clone -b master --single-branch https://github.com/mapbox/mason.git ~/.mason
- sudo ln -s ~/.mason/mason /usr/local/bin/mason
- ls ~/.mason
- ls /usr/local/bin/
- mason install boost 1.58
script:
- cordova -v
- ionic info
- ionic browser list
- ionic browser add crosswalk@14.42.334.0
- cordova plugin add cordova-sqlite-storage
- ionic build android
- ls platforms/android/build/outputs/apk/
- "/bin/cp platforms/android/build/outputs/apk/android-armv7-debug.apk dev/android-armv7-debug.apk"
- sh ./dev/scripts/github.sh
env:
  global:
  - secure: sHVFWJxH6ZKHYEfjj+mk8o/uWdkt+8lQWZtUbpgANPCV55rpEtPrb2LbMVTF78DZVH57yGHCXSig9Bl/RnDVUppMnrwBIY+irz4idzyFcKFC4PFqLiqqegD66w1QNlQKeXFRbkRAgluHtUZz1B03MURY8NhKxW9vJEiwc/wAuoZEnCd30fvRe3khrZU0UDVwqqHiqYCZxsuBCzXv++b85SZ7NAm8mFREKLs0DUPzQN4J2aNJX1km2Xhz5UoU/vtfDVwjssXtBEeg+IDz4EnBdWZE2Ef2XGZKptxfRlDExSvxQNi3+sCtiCHC1vw/Y29oevSL4K3xnAxcerLh0B5ncwyQiHELkhO7er05zoKJdyMnZoRX5bvnDqj6Yk/JhBI+gB8qT8yUl0c+Uy0nJ2d61lVjbxylghd3ZFuH9JJ9rfmjW5+aEvccvhzizC1R8W+XNYb+vy2iEzbilGHxVmU485Tjg3h5vwvYK2C+9efAnrT8TjOL8iZbYZkTZJnbySYSmhgLgjkRO+Tz43zMbODzEQRfqc+W9DjviwPIRv6+fZMdcD1Q0ngMWu936A5lafHfh7+guSFJ+QTWD2TZ7l4cdGuV2B+lNc2tpSOPH0oi6GnHztRAcBcXgEKH9+1jrM7kVdBNPX4q8+IyABSFuQI74p8FAXAPpi5MrRpiTeIAvqQ=
