language: android
sudo: required
branches:
  only:
  - master
deploy:
  skip_cleanup: true
android:
  components:
  - platform-tools
  - build-tools
  - android-22
before_install:
- nvm install 0.12
- npm install -g cordova
- npm install -g ionic
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# https://github.com/systemed/tilemaker
- sudo add-apt-repository ppa:ostogvin/tjo-develop
- sudo apt-get update -q
- sudo apt-get install build-essential 
- sudo apt-get install liblua5.1-0
- sudo apt-get install iblua5.1-0-dev
- sudo apt-get install libprotobuf-dev
- sudo apt-get install libsqlite3-dev
- sudo apt-get install protobuf-compiler
- sudo apt-get install libboost1.58-all-dev
- git clone https://github.com/rpavlik/luabind.git
- export BOOST_ROOT="/usr/include/boost"
- cd luabind
- sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so /usr/lib/
- sudo bjam install
- sudo ln -s /usr/local/lib/libluabindd.so /usr/local/lib/libluabind.so
- sudo ldconfig
script:
- git clone https://github.com/flamed0011/tilemaker.git dev/tilemaker
- cd dev/tilemaker
- make
- make install
- tilemaker --help
- cordova -v
- ionic info
- ionic browser list
- ionic browser add crosswalk@14.42.334.0
- cordova plugin add cordova-sqlite-storage
- ionic build android
- ls platforms/android/build/outputs/apk/
- "/bin/cp platforms/android/build/outputs/apk/android-armv7-debug.apk dev/android-armv7-debug.apk"
- sh ./dev/scripts/github.sh
env:
  global:
  - secure: sHVFWJxH6ZKHYEfjj+mk8o/uWdkt+8lQWZtUbpgANPCV55rpEtPrb2LbMVTF78DZVH57yGHCXSig9Bl/RnDVUppMnrwBIY+irz4idzyFcKFC4PFqLiqqegD66w1QNlQKeXFRbkRAgluHtUZz1B03MURY8NhKxW9vJEiwc/wAuoZEnCd30fvRe3khrZU0UDVwqqHiqYCZxsuBCzXv++b85SZ7NAm8mFREKLs0DUPzQN4J2aNJX1km2Xhz5UoU/vtfDVwjssXtBEeg+IDz4EnBdWZE2Ef2XGZKptxfRlDExSvxQNi3+sCtiCHC1vw/Y29oevSL4K3xnAxcerLh0B5ncwyQiHELkhO7er05zoKJdyMnZoRX5bvnDqj6Yk/JhBI+gB8qT8yUl0c+Uy0nJ2d61lVjbxylghd3ZFuH9JJ9rfmjW5+aEvccvhzizC1R8W+XNYb+vy2iEzbilGHxVmU485Tjg3h5vwvYK2C+9efAnrT8TjOL8iZbYZkTZJnbySYSmhgLgjkRO+Tz43zMbODzEQRfqc+W9DjviwPIRv6+fZMdcD1Q0ngMWu936A5lafHfh7+guSFJ+QTWD2TZ7l4cdGuV2B+lNc2tpSOPH0oi6GnHztRAcBcXgEKH9+1jrM7kVdBNPX4q8+IyABSFuQI74p8FAXAPpi5MrRpiTeIAvqQ=
