language: android
branches:
  only:
  - master
deploy:
  skip_cleanup: true
android:
  components:
  - platform-tools
  - build-tools
  - android-22
before_install:
  - nvm install 0.12
  - npm install -g cordova
  - npm install -g ionic
script:
#- cd mapdis
  - mkdir platforms
  - cordova -v
  - ionic info
  - ionic browser list
  - ionic browser add crosswalk@14.42.334.0
  - cordova plugin add cordova-sqlite-storage
  - grunt build
  - ls platforms/android/build/outputs/apk/ 
  - "/bin/cp platforms/android/build/outputs/apk/android-armv7-debug.apk dev/android-armv7-debug.apk"
  - sh ./dev/scripts/github.sh
 
env:
  global:
  - secure: 636b854bedbf9325e2dc2432d9736817102d1983
